version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "4100:4000"  # SSR con Express corre en el puerto 4000
    depends_on:
      - backend
    networks:
      - pronuncia-net

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "8100:8000"
    networks:
      - pronuncia-net

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pronuncia-net

volumes:
  postgres_data:

networks:
  pronuncia-net:
    driver: bridge
