version: '3.8'

services:
  frontend:
    image: ${IMAGE_FRONTEND}
    container_name: frontend
    restart: always
    expose:
      - "4000"  # usado internamente por nginx
    depends_on:
      - backend
    networks:
      - web

  backend:
    image: ${IMAGE_BACKEND}
    container_name: backend
    restart: always
    expose:
      - "8000"
    networks:
      - web

  nginx:
    image: nginx:stable
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - frontend
    networks:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/lib/letsencrypt
             --email tu-correo@example.com --agree-tos --no-eff-email
             -d especificacionestecnicas.com  -d www.especificacionestecnicas.com "

volumes:
  certbot-etc:
  certbot-var:

networks:
  web:
