version: '3.8'

services:
  frontend:
    image: app_loteria_frontend
    build:
      context: ./frontend
    container_name: frontend_loteria
    restart: always
    ports:
      - "4000:80"  # SSR con Express corre en el puerto 4000
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    image: app_loteria_backend
    build:
      context: ./backend
    container_name: backend_loteria
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - db-data:/app_loteria/backend/data 
    networks:
      - app-net

  postgres:
    image: postgres:16
    container_name: postgres-database-loteria
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydatabase-loteria
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  db-data: 