version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "4000:4000"  # SSR con Express corre en el puerto 4000
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - db-data:/app/backend/data 
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
