version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/
    depends_on:
      - frontend
      - backend
