version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
